//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from fsa15.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="fsa15Parser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface Ifsa15Visitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.fsa15"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFsa15([NotNull] fsa15Parser.Fsa15Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.standardMessageIdentification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStandardMessageIdentification([NotNull] fsa15Parser.StandardMessageIdentificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.multicarrierConsignments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMulticarrierConsignments([NotNull] fsa15Parser.MulticarrierConsignmentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.statusDetails"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatusDetails([NotNull] fsa15Parser.StatusDetailsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.statusDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatusDetail([NotNull] fsa15Parser.StatusDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.otherServiceInformation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOtherServiceInformation([NotNull] fsa15Parser.OtherServiceInformationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.statusDetailsRcs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatusDetailsRcs([NotNull] fsa15Parser.StatusDetailsRcsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.statusDetailsRct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatusDetailsRct([NotNull] fsa15Parser.StatusDetailsRctContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.statusDetailsRcf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatusDetailsRcf([NotNull] fsa15Parser.StatusDetailsRcfContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.statusDetailsBkd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatusDetailsBkd([NotNull] fsa15Parser.StatusDetailsBkdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.statusDetailsMan"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatusDetailsMan([NotNull] fsa15Parser.StatusDetailsManContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.statusDetailsDep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatusDetailsDep([NotNull] fsa15Parser.StatusDetailsDepContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.statusDetailsPre"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatusDetailsPre([NotNull] fsa15Parser.StatusDetailsPreContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.statusDetailsTrm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatusDetailsTrm([NotNull] fsa15Parser.StatusDetailsTrmContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.statusDetailsTfd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatusDetailsTfd([NotNull] fsa15Parser.StatusDetailsTfdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.statusDetailsNfd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatusDetailsNfd([NotNull] fsa15Parser.StatusDetailsNfdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.statusDetailsAwd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatusDetailsAwd([NotNull] fsa15Parser.StatusDetailsAwdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.statusDetailsCcd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatusDetailsCcd([NotNull] fsa15Parser.StatusDetailsCcdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.statusDetailsDlv"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatusDetailsDlv([NotNull] fsa15Parser.StatusDetailsDlvContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.statusDetailsDis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatusDetailsDis([NotNull] fsa15Parser.StatusDetailsDisContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.statusDetailsCrc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatusDetailsCrc([NotNull] fsa15Parser.StatusDetailsCrcContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.statusDetailsDdl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatusDetailsDdl([NotNull] fsa15Parser.StatusDetailsDdlContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.statusDetailsTgc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatusDetailsTgc([NotNull] fsa15Parser.StatusDetailsTgcContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.statusDetailsArr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatusDetailsArr([NotNull] fsa15Parser.StatusDetailsArrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.statusDetailsAwr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatusDetailsAwr([NotNull] fsa15Parser.StatusDetailsAwrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.statusDetailsFoh"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatusDetailsFoh([NotNull] fsa15Parser.StatusDetailsFohContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.otherCustSecurityAndRegulatCtrlInfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOtherCustSecurityAndRegulatCtrlInfo([NotNull] fsa15Parser.OtherCustSecurityAndRegulatCtrlInfoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.consignmentDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConsignmentDetail([NotNull] fsa15Parser.ConsignmentDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.quantityDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuantityDetail([NotNull] fsa15Parser.QuantityDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.movementDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMovementDetail([NotNull] fsa15Parser.MovementDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.movementDetailRcs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMovementDetailRcs([NotNull] fsa15Parser.MovementDetailRcsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.movementDetailRct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMovementDetailRct([NotNull] fsa15Parser.MovementDetailRctContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.movementDetailTrm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMovementDetailTrm([NotNull] fsa15Parser.MovementDetailTrmContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.movementDetailTfd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMovementDetailTfd([NotNull] fsa15Parser.MovementDetailTfdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.movementDetailNfd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMovementDetailNfd([NotNull] fsa15Parser.MovementDetailNfdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.movementDetailAwd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMovementDetailAwd([NotNull] fsa15Parser.MovementDetailAwdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.movementDetailCcd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMovementDetailCcd([NotNull] fsa15Parser.MovementDetailCcdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.movementDetailDlv"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMovementDetailDlv([NotNull] fsa15Parser.MovementDetailDlvContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.movementDetailDdl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMovementDetailDdl([NotNull] fsa15Parser.MovementDetailDdlContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.movementDetailTgc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMovementDetailTgc([NotNull] fsa15Parser.MovementDetailTgcContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.movementDetailFoh"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMovementDetailFoh([NotNull] fsa15Parser.MovementDetailFohContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.movementDetailWithSlant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMovementDetailWithSlant([NotNull] fsa15Parser.MovementDetailWithSlantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.movementDetailWithFlightId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMovementDetailWithFlightId([NotNull] fsa15Parser.MovementDetailWithFlightIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.reportingDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReportingDetail([NotNull] fsa15Parser.ReportingDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.awbIdentification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAwbIdentification([NotNull] fsa15Parser.AwbIdentificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.awbOriginAndDestination"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAwbOriginAndDestination([NotNull] fsa15Parser.AwbOriginAndDestinationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.weightInformation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWeightInformation([NotNull] fsa15Parser.WeightInformationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.volumeDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVolumeDetail([NotNull] fsa15Parser.VolumeDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.densityGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDensityGroup([NotNull] fsa15Parser.DensityGroupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.volumeOrDensity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVolumeOrDensity([NotNull] fsa15Parser.VolumeOrDensityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.volumeOrDensityWithCrlf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVolumeOrDensityWithCrlf([NotNull] fsa15Parser.VolumeOrDensityWithCrlfContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.volumeOrDensityDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVolumeOrDensityDetail([NotNull] fsa15Parser.VolumeOrDensityDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.totalConsignmentPieces"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTotalConsignmentPieces([NotNull] fsa15Parser.TotalConsignmentPiecesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.flightIdentification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFlightIdentification([NotNull] fsa15Parser.FlightIdentificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.timeInformations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTimeInformations([NotNull] fsa15Parser.TimeInformationsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.timeAndVolumeInformation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTimeAndVolumeInformation([NotNull] fsa15Parser.TimeAndVolumeInformationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.timeOfDepartureInformation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTimeOfDepartureInformation([NotNull] fsa15Parser.TimeOfDepartureInformationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.timeOfArrivalInformation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTimeOfArrivalInformation([NotNull] fsa15Parser.TimeOfArrivalInformationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.timeInformation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTimeInformation([NotNull] fsa15Parser.TimeInformationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.timeOfArrivalAndVolume"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTimeOfArrivalAndVolume([NotNull] fsa15Parser.TimeOfArrivalAndVolumeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.dayChangeIndicator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDayChangeIndicator([NotNull] fsa15Parser.DayChangeIndicatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.receivedfromDetailSep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReceivedfromDetailSep([NotNull] fsa15Parser.ReceivedfromDetailSepContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.discrepancyDescription"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDiscrepancyDescription([NotNull] fsa15Parser.DiscrepancyDescriptionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.transferReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTransferReference([NotNull] fsa15Parser.TransferReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.transferredFromDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTransferredFromDetail([NotNull] fsa15Parser.TransferredFromDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.uldDescriptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUldDescriptions([NotNull] fsa15Parser.UldDescriptionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.uldDescription"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUldDescription([NotNull] fsa15Parser.UldDescriptionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.uldIdentification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUldIdentification([NotNull] fsa15Parser.UldIdentificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.uldPositionInformation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUldPositionInformation([NotNull] fsa15Parser.UldPositionInformationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.osiDetails1stLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOsiDetails1stLine([NotNull] fsa15Parser.OsiDetails1stLineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.osiDetails2stLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOsiDetails2stLine([NotNull] fsa15Parser.OsiDetails2stLineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.receivedFromDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReceivedFromDetail([NotNull] fsa15Parser.ReceivedFromDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.transferredName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTransferredName([NotNull] fsa15Parser.TransferredNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.receivedName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReceivedName([NotNull] fsa15Parser.ReceivedNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.notificationToDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNotificationToDetail([NotNull] fsa15Parser.NotificationToDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.deliveryToDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeliveryToDetail([NotNull] fsa15Parser.DeliveryToDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.otherCustSecurityAndRegulatCtrlInfoDet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOtherCustSecurityAndRegulatCtrlInfoDet([NotNull] fsa15Parser.OtherCustSecurityAndRegulatCtrlInfoDetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.standardMessageIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStandardMessageIdentifier([NotNull] fsa15Parser.StandardMessageIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.messageTypeVersionNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageTypeVersionNumber([NotNull] fsa15Parser.MessageTypeVersionNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.lineIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLineIdentifier([NotNull] fsa15Parser.LineIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.airlinePrefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirlinePrefix([NotNull] fsa15Parser.AirlinePrefixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.awbSerialNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAwbSerialNumber([NotNull] fsa15Parser.AwbSerialNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.airportCodeOfOrigin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirportCodeOfOrigin([NotNull] fsa15Parser.AirportCodeOfOriginContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.airportCodeOfDestitation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirportCodeOfDestitation([NotNull] fsa15Parser.AirportCodeOfDestitationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.airportCodeOfArrival"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirportCodeOfArrival([NotNull] fsa15Parser.AirportCodeOfArrivalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.airportCodeOfDeparture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirportCodeOfDeparture([NotNull] fsa15Parser.AirportCodeOfDepartureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.airportCodeOfNotification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirportCodeOfNotification([NotNull] fsa15Parser.AirportCodeOfNotificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.airportCodeOfDelivery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirportCodeOfDelivery([NotNull] fsa15Parser.AirportCodeOfDeliveryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.airportCodeOfClearance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirportCodeOfClearance([NotNull] fsa15Parser.AirportCodeOfClearanceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.airportCodeOfReporting"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirportCodeOfReporting([NotNull] fsa15Parser.AirportCodeOfReportingContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.airportCodeOfDeliveryToConsigneesDoor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirportCodeOfDeliveryToConsigneesDoor([NotNull] fsa15Parser.AirportCodeOfDeliveryToConsigneesDoorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.transferManifestNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTransferManifestNumber([NotNull] fsa15Parser.TransferManifestNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.shipmentDescriptionCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShipmentDescriptionCode([NotNull] fsa15Parser.ShipmentDescriptionCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.dayChangeIndicatorCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDayChangeIndicatorCode([NotNull] fsa15Parser.DayChangeIndicatorCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.typeOfTimeIndicator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeOfTimeIndicator([NotNull] fsa15Parser.TypeOfTimeIndicatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.volumeCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVolumeCode([NotNull] fsa15Parser.VolumeCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.volumeAmount"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVolumeAmount([NotNull] fsa15Parser.VolumeAmountContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.densityIndicator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDensityIndicator([NotNull] fsa15Parser.DensityIndicatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.receivingCarrier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReceivingCarrier([NotNull] fsa15Parser.ReceivingCarrierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.uldLoadingIndicator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUldLoadingIndicator([NotNull] fsa15Parser.UldLoadingIndicatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.densityGroupInner"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDensityGroupInner([NotNull] fsa15Parser.DensityGroupInnerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.discrepancyCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDiscrepancyCode([NotNull] fsa15Parser.DiscrepancyCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.dayOfReceipt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDayOfReceipt([NotNull] fsa15Parser.DayOfReceiptContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.dayOfTransfer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDayOfTransfer([NotNull] fsa15Parser.DayOfTransferContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.dayOfScheduledArrival"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDayOfScheduledArrival([NotNull] fsa15Parser.DayOfScheduledArrivalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.dayOfScheduledDeparture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDayOfScheduledDeparture([NotNull] fsa15Parser.DayOfScheduledDepartureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.dayOfNotification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDayOfNotification([NotNull] fsa15Parser.DayOfNotificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.dayOfDelivery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDayOfDelivery([NotNull] fsa15Parser.DayOfDeliveryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.dayOfClearance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDayOfClearance([NotNull] fsa15Parser.DayOfClearanceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.dayOfReporting"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDayOfReporting([NotNull] fsa15Parser.DayOfReportingContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.dayOfDeliveryToConsigneesDoor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDayOfDeliveryToConsigneesDoor([NotNull] fsa15Parser.DayOfDeliveryToConsigneesDoorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.monthOfReceipt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMonthOfReceipt([NotNull] fsa15Parser.MonthOfReceiptContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.monthOfTransfer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMonthOfTransfer([NotNull] fsa15Parser.MonthOfTransferContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.monthOfScheduledArrival"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMonthOfScheduledArrival([NotNull] fsa15Parser.MonthOfScheduledArrivalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.monthOfScheduledDeparture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMonthOfScheduledDeparture([NotNull] fsa15Parser.MonthOfScheduledDepartureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.monthOfNotification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMonthOfNotification([NotNull] fsa15Parser.MonthOfNotificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.monthOfClearance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMonthOfClearance([NotNull] fsa15Parser.MonthOfClearanceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.monthOfDelivery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMonthOfDelivery([NotNull] fsa15Parser.MonthOfDeliveryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.monthOfReporting"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMonthOfReporting([NotNull] fsa15Parser.MonthOfReportingContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.monthOfDeliveryToConsigneesDoor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMonthOfDeliveryToConsigneesDoor([NotNull] fsa15Parser.MonthOfDeliveryToConsigneesDoorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.actualTimeOfGivenStatusEvent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActualTimeOfGivenStatusEvent([NotNull] fsa15Parser.ActualTimeOfGivenStatusEventContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.time"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTime([NotNull] fsa15Parser.TimeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.airportCodeOfReceipt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirportCodeOfReceipt([NotNull] fsa15Parser.AirportCodeOfReceiptContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.airportCodeOfTransfer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirportCodeOfTransfer([NotNull] fsa15Parser.AirportCodeOfTransferContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.flightNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFlightNumber([NotNull] fsa15Parser.FlightNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.carrierCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCarrierCode([NotNull] fsa15Parser.CarrierCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.transferringCarrier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTransferringCarrier([NotNull] fsa15Parser.TransferringCarrierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.uldType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUldType([NotNull] fsa15Parser.UldTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.uldSerialNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUldSerialNumber([NotNull] fsa15Parser.UldSerialNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.uldOwnerCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUldOwnerCode([NotNull] fsa15Parser.UldOwnerCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.weightCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWeightCode([NotNull] fsa15Parser.WeightCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.weight"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWeight([NotNull] fsa15Parser.WeightContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.numberOfPieces"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberOfPieces([NotNull] fsa15Parser.NumberOfPiecesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.isoCountryCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIsoCountryCode([NotNull] fsa15Parser.IsoCountryCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.informationIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInformationIdentifier([NotNull] fsa15Parser.InformationIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.custSecurityAndRegulatCtrlInfoId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCustSecurityAndRegulatCtrlInfoId([NotNull] fsa15Parser.CustSecurityAndRegulatCtrlInfoIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.supplemCustSecurityAndRegulatCtrlInfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSupplemCustSecurityAndRegulatCtrlInfo([NotNull] fsa15Parser.SupplemCustSecurityAndRegulatCtrlInfoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.osiDescription"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOsiDescription([NotNull] fsa15Parser.OsiDescriptionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsa15Parser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitName([NotNull] fsa15Parser.NameContext context);
}
