//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from fsr1.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="fsr1Parser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface Ifsr1Visitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsr1Parser.fsr1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFsr1([NotNull] fsr1Parser.Fsr1Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsr1Parser.standardMessageIdentification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStandardMessageIdentification([NotNull] fsr1Parser.StandardMessageIdentificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsr1Parser.consignmentDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConsignmentDetail([NotNull] fsr1Parser.ConsignmentDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsr1Parser.flightDetails"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFlightDetails([NotNull] fsr1Parser.FlightDetailsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsr1Parser.otherServiceInformation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOtherServiceInformation([NotNull] fsr1Parser.OtherServiceInformationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsr1Parser.awbIdentification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAwbIdentification([NotNull] fsr1Parser.AwbIdentificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsr1Parser.awbOriginAndDestination"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAwbOriginAndDestination([NotNull] fsr1Parser.AwbOriginAndDestinationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsr1Parser.quantityDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuantityDetail([NotNull] fsr1Parser.QuantityDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsr1Parser.totalConsignmentPieces"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTotalConsignmentPieces([NotNull] fsr1Parser.TotalConsignmentPiecesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsr1Parser.weightDetails"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWeightDetails([NotNull] fsr1Parser.WeightDetailsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsr1Parser.natureOfGoods"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNatureOfGoods([NotNull] fsr1Parser.NatureOfGoodsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsr1Parser.flightIdentification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFlightIdentification([NotNull] fsr1Parser.FlightIdentificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsr1Parser.airportsOfDepartureAndArrival"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirportsOfDepartureAndArrival([NotNull] fsr1Parser.AirportsOfDepartureAndArrivalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsr1Parser.osiDetails1stLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOsiDetails1stLine([NotNull] fsr1Parser.OsiDetails1stLineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsr1Parser.osiDetails2stLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOsiDetails2stLine([NotNull] fsr1Parser.OsiDetails2stLineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsr1Parser.flightDate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFlightDate([NotNull] fsr1Parser.FlightDateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsr1Parser.standardMessageIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStandardMessageIdentifier([NotNull] fsr1Parser.StandardMessageIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsr1Parser.lineIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLineIdentifier([NotNull] fsr1Parser.LineIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsr1Parser.airlinePrefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirlinePrefix([NotNull] fsr1Parser.AirlinePrefixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsr1Parser.awbSerialNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAwbSerialNumber([NotNull] fsr1Parser.AwbSerialNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsr1Parser.shipmentDescriptionCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShipmentDescriptionCode([NotNull] fsr1Parser.ShipmentDescriptionCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsr1Parser.numberOfPieces"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberOfPieces([NotNull] fsr1Parser.NumberOfPiecesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsr1Parser.weightCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWeightCode([NotNull] fsr1Parser.WeightCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsr1Parser.weight"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWeight([NotNull] fsr1Parser.WeightContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsr1Parser.carrierCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCarrierCode([NotNull] fsr1Parser.CarrierCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsr1Parser.flightNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFlightNumber([NotNull] fsr1Parser.FlightNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsr1Parser.dayOfScheduledDeparture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDayOfScheduledDeparture([NotNull] fsr1Parser.DayOfScheduledDepartureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsr1Parser.monthOfScheduledDeparture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMonthOfScheduledDeparture([NotNull] fsr1Parser.MonthOfScheduledDepartureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsr1Parser.airportCodeOfDeparture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirportCodeOfDeparture([NotNull] fsr1Parser.AirportCodeOfDepartureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsr1Parser.airportCodeOfArrival"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirportCodeOfArrival([NotNull] fsr1Parser.AirportCodeOfArrivalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsr1Parser.airportCodeOfOrigin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirportCodeOfOrigin([NotNull] fsr1Parser.AirportCodeOfOriginContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsr1Parser.airportCodeOfDestitation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirportCodeOfDestitation([NotNull] fsr1Parser.AirportCodeOfDestitationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsr1Parser.manifestDescriptionOfGoods"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitManifestDescriptionOfGoods([NotNull] fsr1Parser.ManifestDescriptionOfGoodsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsr1Parser.osiDescription"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOsiDescription([NotNull] fsr1Parser.OsiDescriptionContext context);
}
