//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ffm8.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ffm8Parser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface Iffm8Visitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.ffm8"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFfm8([NotNull] ffm8Parser.Ffm8Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.standardMessageIdentification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStandardMessageIdentification([NotNull] ffm8Parser.StandardMessageIdentificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.flightIdAndPointOfLoading"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFlightIdAndPointOfLoading([NotNull] ffm8Parser.FlightIdAndPointOfLoadingContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.destinationHeader"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDestinationHeader([NotNull] ffm8Parser.DestinationHeaderContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.manifestCompleteIndicator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitManifestCompleteIndicator([NotNull] ffm8Parser.ManifestCompleteIndicatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.pointOfUnloading"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPointOfUnloading([NotNull] ffm8Parser.PointOfUnloadingContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.bulkLoadedCargo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBulkLoadedCargo([NotNull] ffm8Parser.BulkLoadedCargoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.uldLoadedCargo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUldLoadedCargo([NotNull] ffm8Parser.UldLoadedCargoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.consignments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConsignments([NotNull] ffm8Parser.ConsignmentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.uldDescription"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUldDescription([NotNull] ffm8Parser.UldDescriptionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.uldMovementInformation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUldMovementInformation([NotNull] ffm8Parser.UldMovementInformationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.uldUtilisationDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUldUtilisationDetail([NotNull] ffm8Parser.UldUtilisationDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.otherServiceInformation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOtherServiceInformation([NotNull] ffm8Parser.OtherServiceInformationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.customsOrigin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCustomsOrigin([NotNull] ffm8Parser.CustomsOriginContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.otherCustSecurityAndRegulatCtrlInfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOtherCustSecurityAndRegulatCtrlInfo([NotNull] ffm8Parser.OtherCustSecurityAndRegulatCtrlInfoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.flightIdentification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFlightIdentification([NotNull] ffm8Parser.FlightIdentificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.firstPointOfArrivalInformation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFirstPointOfArrivalInformation([NotNull] ffm8Parser.FirstPointOfArrivalInformationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.nilCargoIndication"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNilCargoIndication([NotNull] ffm8Parser.NilCargoIndicationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.aircraftIdentification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAircraftIdentification([NotNull] ffm8Parser.AircraftIdentificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.arrivalInformation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrivalInformation([NotNull] ffm8Parser.ArrivalInformationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.departureInformation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDepartureInformation([NotNull] ffm8Parser.DepartureInformationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.arrivalInformationDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrivalInformationDetail([NotNull] ffm8Parser.ArrivalInformationDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.departureInformationDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDepartureInformationDetail([NotNull] ffm8Parser.DepartureInformationDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.awbIdentification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAwbIdentification([NotNull] ffm8Parser.AwbIdentificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.awbOriginAndDestination"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAwbOriginAndDestination([NotNull] ffm8Parser.AwbOriginAndDestinationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.quantityDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuantityDetail([NotNull] ffm8Parser.QuantityDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.volumeDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVolumeDetail([NotNull] ffm8Parser.VolumeDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.densityGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDensityGroup([NotNull] ffm8Parser.DensityGroupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.totalWeightDetails"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTotalWeightDetails([NotNull] ffm8Parser.TotalWeightDetailsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.totalConsignmentPieces"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTotalConsignmentPieces([NotNull] ffm8Parser.TotalConsignmentPiecesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.shrs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShrs([NotNull] ffm8Parser.ShrsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.specialHandlingRequirements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpecialHandlingRequirements([NotNull] ffm8Parser.SpecialHandlingRequirementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.consignmentDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConsignmentDetail([NotNull] ffm8Parser.ConsignmentDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.dimensionsInformation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDimensionsInformation([NotNull] ffm8Parser.DimensionsInformationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.consignmentOnwardMovementInfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConsignmentOnwardMovementInfo([NotNull] ffm8Parser.ConsignmentOnwardMovementInfoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.consignmentOnward"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConsignmentOnward([NotNull] ffm8Parser.ConsignmentOnwardContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.onwardRoutingDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOnwardRoutingDetail([NotNull] ffm8Parser.OnwardRoutingDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.onwardBookingDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOnwardBookingDetail([NotNull] ffm8Parser.OnwardBookingDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.osiDetails1stLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOsiDetails1stLine([NotNull] ffm8Parser.OsiDetails1stLineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.osiDetails2stLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOsiDetails2stLine([NotNull] ffm8Parser.OsiDetails2stLineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.uldOnwardRoutingDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUldOnwardRoutingDetail([NotNull] ffm8Parser.UldOnwardRoutingDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.uldOnwardBookingDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUldOnwardBookingDetail([NotNull] ffm8Parser.UldOnwardBookingDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.uldIdentification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUldIdentification([NotNull] ffm8Parser.UldIdentificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.uldPositionInformation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUldPositionInformation([NotNull] ffm8Parser.UldPositionInformationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.uldRemarks"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUldRemarks([NotNull] ffm8Parser.UldRemarksContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.movementPriority"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMovementPriority([NotNull] ffm8Parser.MovementPriorityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.natureOfGoods"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNatureOfGoods([NotNull] ffm8Parser.NatureOfGoodsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.dimensions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDimensions([NotNull] ffm8Parser.DimensionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.dimensionsDetails"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDimensionsDetails([NotNull] ffm8Parser.DimensionsDetailsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.otherCustSecurityAndRegulatCtrlInfoDet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOtherCustSecurityAndRegulatCtrlInfoDet([NotNull] ffm8Parser.OtherCustSecurityAndRegulatCtrlInfoDetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.standardMessageIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStandardMessageIdentifier([NotNull] ffm8Parser.StandardMessageIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.messageTypeVersionNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageTypeVersionNumber([NotNull] ffm8Parser.MessageTypeVersionNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.messageSequenceNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageSequenceNumber([NotNull] ffm8Parser.MessageSequenceNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.lineIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLineIdentifier([NotNull] ffm8Parser.LineIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.airlinePrefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirlinePrefix([NotNull] ffm8Parser.AirlinePrefixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.awbSerialNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAwbSerialNumber([NotNull] ffm8Parser.AwbSerialNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.airportCodeOfLoading"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirportCodeOfLoading([NotNull] ffm8Parser.AirportCodeOfLoadingContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.airportCodeOfUnloading"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirportCodeOfUnloading([NotNull] ffm8Parser.AirportCodeOfUnloadingContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.airportCodeOfOrigin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirportCodeOfOrigin([NotNull] ffm8Parser.AirportCodeOfOriginContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.airportCodeOfDestitation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirportCodeOfDestitation([NotNull] ffm8Parser.AirportCodeOfDestitationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.airportCodeOfArrival"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirportCodeOfArrival([NotNull] ffm8Parser.AirportCodeOfArrivalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.airportCodeOfNextDestination"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirportCodeOfNextDestination([NotNull] ffm8Parser.AirportCodeOfNextDestinationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.uldVolumeAvailableCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUldVolumeAvailableCode([NotNull] ffm8Parser.UldVolumeAvailableCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.nilCargoCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNilCargoCode([NotNull] ffm8Parser.NilCargoCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.movementPriorityCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMovementPriorityCode([NotNull] ffm8Parser.MovementPriorityCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.shipmentDescriptionCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShipmentDescriptionCode([NotNull] ffm8Parser.ShipmentDescriptionCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.volumeCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVolumeCode([NotNull] ffm8Parser.VolumeCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.volumeAmount"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVolumeAmount([NotNull] ffm8Parser.VolumeAmountContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.densityIndicator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDensityIndicator([NotNull] ffm8Parser.DensityIndicatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.densityGroupInner"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDensityGroupInner([NotNull] ffm8Parser.DensityGroupInnerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.dayOfScheduledArrival"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDayOfScheduledArrival([NotNull] ffm8Parser.DayOfScheduledArrivalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.monthOfScheduledArrival"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMonthOfScheduledArrival([NotNull] ffm8Parser.MonthOfScheduledArrivalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.timeOfScheduledArrival"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTimeOfScheduledArrival([NotNull] ffm8Parser.TimeOfScheduledArrivalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.dayOfScheduledDeparture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDayOfScheduledDeparture([NotNull] ffm8Parser.DayOfScheduledDepartureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.monthOfScheduledDeparture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMonthOfScheduledDeparture([NotNull] ffm8Parser.MonthOfScheduledDepartureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.timeOfScheduledDeparture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTimeOfScheduledDeparture([NotNull] ffm8Parser.TimeOfScheduledDepartureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.flightNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFlightNumber([NotNull] ffm8Parser.FlightNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.customsOriginCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCustomsOriginCode([NotNull] ffm8Parser.CustomsOriginCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.carrierCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCarrierCode([NotNull] ffm8Parser.CarrierCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.uldType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUldType([NotNull] ffm8Parser.UldTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.uldSerialNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUldSerialNumber([NotNull] ffm8Parser.UldSerialNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.uldOwnerCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUldOwnerCode([NotNull] ffm8Parser.UldOwnerCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.uldLoadingIndicator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUldLoadingIndicator([NotNull] ffm8Parser.UldLoadingIndicatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.measurementUnitCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMeasurementUnitCode([NotNull] ffm8Parser.MeasurementUnitCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.lengthDimension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLengthDimension([NotNull] ffm8Parser.LengthDimensionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.widthDimension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWidthDimension([NotNull] ffm8Parser.WidthDimensionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.heightDimension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHeightDimension([NotNull] ffm8Parser.HeightDimensionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.weightCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWeightCode([NotNull] ffm8Parser.WeightCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.weight"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWeight([NotNull] ffm8Parser.WeightContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.numberOfPieces"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberOfPieces([NotNull] ffm8Parser.NumberOfPiecesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.specialHandlingCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpecialHandlingCode([NotNull] ffm8Parser.SpecialHandlingCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.isoCountryCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIsoCountryCode([NotNull] ffm8Parser.IsoCountryCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.informationIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInformationIdentifier([NotNull] ffm8Parser.InformationIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.custSecurityAndRegulatCtrlInfoId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCustSecurityAndRegulatCtrlInfoId([NotNull] ffm8Parser.CustSecurityAndRegulatCtrlInfoIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.endOfMessageCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEndOfMessageCode([NotNull] ffm8Parser.EndOfMessageCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.aircraftRegistration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAircraftRegistration([NotNull] ffm8Parser.AircraftRegistrationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.supplemCustSecurityAndRegulatCtrlInfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSupplemCustSecurityAndRegulatCtrlInfo([NotNull] ffm8Parser.SupplemCustSecurityAndRegulatCtrlInfoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.manifestDescriptionOfGoods"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitManifestDescriptionOfGoods([NotNull] ffm8Parser.ManifestDescriptionOfGoodsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.uldRemarksDescription"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUldRemarksDescription([NotNull] ffm8Parser.UldRemarksDescriptionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffm8Parser.osiDescription"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOsiDescription([NotNull] ffm8Parser.OsiDescriptionContext context);
}
