//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from fsr.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="fsrParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface IfsrVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsrParser.fsr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFsr([NotNull] fsrParser.FsrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsrParser.standardMessageIdentification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStandardMessageIdentification([NotNull] fsrParser.StandardMessageIdentificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsrParser.consignmentDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConsignmentDetail([NotNull] fsrParser.ConsignmentDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsrParser.flightDetails"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFlightDetails([NotNull] fsrParser.FlightDetailsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsrParser.otherServiceInformation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOtherServiceInformation([NotNull] fsrParser.OtherServiceInformationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsrParser.awbIdentification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAwbIdentification([NotNull] fsrParser.AwbIdentificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsrParser.awbOriginAndDestination"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAwbOriginAndDestination([NotNull] fsrParser.AwbOriginAndDestinationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsrParser.quantityDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuantityDetail([NotNull] fsrParser.QuantityDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsrParser.totalConsignmentPieces"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTotalConsignmentPieces([NotNull] fsrParser.TotalConsignmentPiecesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsrParser.weightDetails"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWeightDetails([NotNull] fsrParser.WeightDetailsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsrParser.natureOfGoods"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNatureOfGoods([NotNull] fsrParser.NatureOfGoodsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsrParser.flightIdentification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFlightIdentification([NotNull] fsrParser.FlightIdentificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsrParser.airportsOfDepartureAndArrival"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirportsOfDepartureAndArrival([NotNull] fsrParser.AirportsOfDepartureAndArrivalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsrParser.osiDetails1stLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOsiDetails1stLine([NotNull] fsrParser.OsiDetails1stLineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsrParser.osiDetails2stLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOsiDetails2stLine([NotNull] fsrParser.OsiDetails2stLineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsrParser.flightDate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFlightDate([NotNull] fsrParser.FlightDateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsrParser.standardMessageIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStandardMessageIdentifier([NotNull] fsrParser.StandardMessageIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsrParser.lineIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLineIdentifier([NotNull] fsrParser.LineIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsrParser.airlinePrefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirlinePrefix([NotNull] fsrParser.AirlinePrefixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsrParser.awbSerialNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAwbSerialNumber([NotNull] fsrParser.AwbSerialNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsrParser.shipmentDescriptionCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShipmentDescriptionCode([NotNull] fsrParser.ShipmentDescriptionCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsrParser.numberOfPieces"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberOfPieces([NotNull] fsrParser.NumberOfPiecesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsrParser.weightCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWeightCode([NotNull] fsrParser.WeightCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsrParser.weight"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWeight([NotNull] fsrParser.WeightContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsrParser.carrierCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCarrierCode([NotNull] fsrParser.CarrierCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsrParser.flightNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFlightNumber([NotNull] fsrParser.FlightNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsrParser.dayOfScheduledDeparture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDayOfScheduledDeparture([NotNull] fsrParser.DayOfScheduledDepartureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsrParser.monthOfScheduledDeparture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMonthOfScheduledDeparture([NotNull] fsrParser.MonthOfScheduledDepartureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsrParser.airportCodeOfDeparture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirportCodeOfDeparture([NotNull] fsrParser.AirportCodeOfDepartureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsrParser.airportCodeOfArrival"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirportCodeOfArrival([NotNull] fsrParser.AirportCodeOfArrivalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsrParser.airportCodeOfOrigin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirportCodeOfOrigin([NotNull] fsrParser.AirportCodeOfOriginContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsrParser.airportCodeOfDestitation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirportCodeOfDestitation([NotNull] fsrParser.AirportCodeOfDestitationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsrParser.manifestDescriptionOfGoods"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitManifestDescriptionOfGoods([NotNull] fsrParser.ManifestDescriptionOfGoodsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fsrParser.osiDescription"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOsiDescription([NotNull] fsrParser.OsiDescriptionContext context);
}
