//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ffa4.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ffa4Parser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface Iffa4Visitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.ffa4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFfa4([NotNull] ffa4Parser.Ffa4Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.standardMessageIdentification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStandardMessageIdentification([NotNull] ffa4Parser.StandardMessageIdentificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.consignmentDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConsignmentDetail([NotNull] ffa4Parser.ConsignmentDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.flightDetails"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFlightDetails([NotNull] ffa4Parser.FlightDetailsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.specialServiceRequest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpecialServiceRequest([NotNull] ffa4Parser.SpecialServiceRequestContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.otherServiceInformation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOtherServiceInformation([NotNull] ffa4Parser.OtherServiceInformationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.bookingReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBookingReference([NotNull] ffa4Parser.BookingReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.shipmentReferenceInformation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShipmentReferenceInformation([NotNull] ffa4Parser.ShipmentReferenceInformationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.flightInfoDetails"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFlightInfoDetails([NotNull] ffa4Parser.FlightInfoDetailsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.flightIdentification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFlightIdentification([NotNull] ffa4Parser.FlightIdentificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.airportsOfDepartureAndArrival"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirportsOfDepartureAndArrival([NotNull] ffa4Parser.AirportsOfDepartureAndArrivalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.awbIdentification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAwbIdentification([NotNull] ffa4Parser.AwbIdentificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.awbOriginAndDestination"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAwbOriginAndDestination([NotNull] ffa4Parser.AwbOriginAndDestinationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.quantityDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuantityDetail([NotNull] ffa4Parser.QuantityDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.volumeDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVolumeDetail([NotNull] ffa4Parser.VolumeDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.densityGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDensityGroup([NotNull] ffa4Parser.DensityGroupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.totalConsignmentPieces"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTotalConsignmentPieces([NotNull] ffa4Parser.TotalConsignmentPiecesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.shrs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShrs([NotNull] ffa4Parser.ShrsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.specialHandlingRequirements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpecialHandlingRequirements([NotNull] ffa4Parser.SpecialHandlingRequirementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.ssrDetails1stLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSsrDetails1stLine([NotNull] ffa4Parser.SsrDetails1stLineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.ssrDetails2stLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSsrDetails2stLine([NotNull] ffa4Parser.SsrDetails2stLineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.osiDetails1stLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOsiDetails1stLine([NotNull] ffa4Parser.OsiDetails1stLineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.osiDetails2stLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOsiDetails2stLine([NotNull] ffa4Parser.OsiDetails2stLineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.natureOfGoods"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNatureOfGoods([NotNull] ffa4Parser.NatureOfGoodsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.requestingOfficeMessageAddress"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRequestingOfficeMessageAddress([NotNull] ffa4Parser.RequestingOfficeMessageAddressContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.rofr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRofr([NotNull] ffa4Parser.RofrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.requestingOfficeFileReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRequestingOfficeFileReference([NotNull] ffa4Parser.RequestingOfficeFileReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.requestingParticipantIdentification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRequestingParticipantIdentification([NotNull] ffa4Parser.RequestingParticipantIdentificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.supplementary1or2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSupplementary1or2([NotNull] ffa4Parser.Supplementary1or2Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.supplementaryShipmentInformation1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSupplementaryShipmentInformation1([NotNull] ffa4Parser.SupplementaryShipmentInformation1Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.supplementaryShipmentInformation2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSupplementaryShipmentInformation2([NotNull] ffa4Parser.SupplementaryShipmentInformation2Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.standardMessageIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStandardMessageIdentifier([NotNull] ffa4Parser.StandardMessageIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.messageTypeVersionNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageTypeVersionNumber([NotNull] ffa4Parser.MessageTypeVersionNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.lineIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLineIdentifier([NotNull] ffa4Parser.LineIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.spaceAllocationCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpaceAllocationCode([NotNull] ffa4Parser.SpaceAllocationCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.airlinePrefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirlinePrefix([NotNull] ffa4Parser.AirlinePrefixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.awbSerialNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAwbSerialNumber([NotNull] ffa4Parser.AwbSerialNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.airportCodeOfDeparture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirportCodeOfDeparture([NotNull] ffa4Parser.AirportCodeOfDepartureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.airportCodeOfOrigin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirportCodeOfOrigin([NotNull] ffa4Parser.AirportCodeOfOriginContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.airportCodeOfDestitation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirportCodeOfDestitation([NotNull] ffa4Parser.AirportCodeOfDestitationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.airportCodeOfArrival"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirportCodeOfArrival([NotNull] ffa4Parser.AirportCodeOfArrivalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.shipmentDescriptionCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShipmentDescriptionCode([NotNull] ffa4Parser.ShipmentDescriptionCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.volumeCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVolumeCode([NotNull] ffa4Parser.VolumeCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.volumeAmount"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVolumeAmount([NotNull] ffa4Parser.VolumeAmountContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.densityIndicator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDensityIndicator([NotNull] ffa4Parser.DensityIndicatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.densityGroupInner"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDensityGroupInner([NotNull] ffa4Parser.DensityGroupInnerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.dayOfScheduledDeparture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDayOfScheduledDeparture([NotNull] ffa4Parser.DayOfScheduledDepartureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.monthOfScheduledDeparture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMonthOfScheduledDeparture([NotNull] ffa4Parser.MonthOfScheduledDepartureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.flightNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFlightNumber([NotNull] ffa4Parser.FlightNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.carrierCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCarrierCode([NotNull] ffa4Parser.CarrierCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.weightCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWeightCode([NotNull] ffa4Parser.WeightCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.weight"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWeight([NotNull] ffa4Parser.WeightContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.numberOfPieces"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberOfPieces([NotNull] ffa4Parser.NumberOfPiecesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.specialHandlingCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpecialHandlingCode([NotNull] ffa4Parser.SpecialHandlingCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.airportCityCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirportCityCode([NotNull] ffa4Parser.AirportCityCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.officeFunctionDesignator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOfficeFunctionDesignator([NotNull] ffa4Parser.OfficeFunctionDesignatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.companyDesignator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompanyDesignator([NotNull] ffa4Parser.CompanyDesignatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.participantIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParticipantIdentifier([NotNull] ffa4Parser.ParticipantIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.participantCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParticipantCode([NotNull] ffa4Parser.ParticipantCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.manifestDescriptionOfGoods"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitManifestDescriptionOfGoods([NotNull] ffa4Parser.ManifestDescriptionOfGoodsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.ssrDescription"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSsrDescription([NotNull] ffa4Parser.SsrDescriptionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.osiDescription"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOsiDescription([NotNull] ffa4Parser.OsiDescriptionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.referenceNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReferenceNumber([NotNull] ffa4Parser.ReferenceNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.innerSupplementaryShipmentInformation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInnerSupplementaryShipmentInformation([NotNull] ffa4Parser.InnerSupplementaryShipmentInformationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ffa4Parser.fileReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFileReference([NotNull] ffa4Parser.FileReferenceContext context);
}
