//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from fwb17.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="fwb17Parser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface Ifwb17Visitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.fwb17"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFwb17([NotNull] fwb17Parser.Fwb17Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.standardMessageIdentification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStandardMessageIdentification([NotNull] fwb17Parser.StandardMessageIdentificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.awbConsignmentDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAwbConsignmentDetail([NotNull] fwb17Parser.AwbConsignmentDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.flightBookings"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFlightBookings([NotNull] fwb17Parser.FlightBookingsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.routing"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRouting([NotNull] fwb17Parser.RoutingContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.shipper"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShipper([NotNull] fwb17Parser.ShipperContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.consignee"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConsignee([NotNull] fwb17Parser.ConsigneeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.agent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAgent([NotNull] fwb17Parser.AgentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.specialServiceRequest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpecialServiceRequest([NotNull] fwb17Parser.SpecialServiceRequestContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.alsoNotify"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlsoNotify([NotNull] fwb17Parser.AlsoNotifyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.accountingInformation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccountingInformation([NotNull] fwb17Parser.AccountingInformationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.chargeDeclarations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChargeDeclarations([NotNull] fwb17Parser.ChargeDeclarationsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.rateDescription"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRateDescription([NotNull] fwb17Parser.RateDescriptionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.otherCharges"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOtherCharges([NotNull] fwb17Parser.OtherChargesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.prepaidChargeSummary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrepaidChargeSummary([NotNull] fwb17Parser.PrepaidChargeSummaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.collectChargeSummary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCollectChargeSummary([NotNull] fwb17Parser.CollectChargeSummaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.shippersCertification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShippersCertification([NotNull] fwb17Parser.ShippersCertificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.carriersExecution"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCarriersExecution([NotNull] fwb17Parser.CarriersExecutionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.otherServiceInformation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOtherServiceInformation([NotNull] fwb17Parser.OtherServiceInformationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.ccChargesInDestinationCurrency"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCcChargesInDestinationCurrency([NotNull] fwb17Parser.CcChargesInDestinationCurrencyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.senderReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSenderReference([NotNull] fwb17Parser.SenderReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.customsOrigin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCustomsOrigin([NotNull] fwb17Parser.CustomsOriginContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.commissionInformation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommissionInformation([NotNull] fwb17Parser.CommissionInformationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.salesIncentiveInformation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSalesIncentiveInformation([NotNull] fwb17Parser.SalesIncentiveInformationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.agentReferenceData"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAgentReferenceData([NotNull] fwb17Parser.AgentReferenceDataContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.specialHandlingDetails"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpecialHandlingDetails([NotNull] fwb17Parser.SpecialHandlingDetailsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.nominatedHandlingParty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNominatedHandlingParty([NotNull] fwb17Parser.NominatedHandlingPartyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.shipmentReferenceInformation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShipmentReferenceInformation([NotNull] fwb17Parser.ShipmentReferenceInformationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.otherParticipantInformation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOtherParticipantInformation([NotNull] fwb17Parser.OtherParticipantInformationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.otherCustSecurityAndRegulatCtrlInfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOtherCustSecurityAndRegulatCtrlInfo([NotNull] fwb17Parser.OtherCustSecurityAndRegulatCtrlInfoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.rateDescriptionItems"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRateDescriptionItems([NotNull] fwb17Parser.RateDescriptionItemsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.chargeLineCount"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChargeLineCount([NotNull] fwb17Parser.ChargeLineCountContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.elementFrom3To10"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElementFrom3To10([NotNull] fwb17Parser.ElementFrom3To10Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.elementFrom11To19"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElementFrom11To19([NotNull] fwb17Parser.ElementFrom11To19Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.numberOfPiecesRcpDetails"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberOfPiecesRcpDetails([NotNull] fwb17Parser.NumberOfPiecesRcpDetailsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.grossWeightDetails"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGrossWeightDetails([NotNull] fwb17Parser.GrossWeightDetailsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.rateClassDetails"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRateClassDetails([NotNull] fwb17Parser.RateClassDetailsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.commodityItemNumberDetails"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommodityItemNumberDetails([NotNull] fwb17Parser.CommodityItemNumberDetailsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.chargeableWeightDetails"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChargeableWeightDetails([NotNull] fwb17Parser.ChargeableWeightDetailsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.rateChargeDetails"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRateChargeDetails([NotNull] fwb17Parser.RateChargeDetailsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.totalDetails"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTotalDetails([NotNull] fwb17Parser.TotalDetailsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.goodsDescription"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGoodsDescription([NotNull] fwb17Parser.GoodsDescriptionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.goodsConsolidation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGoodsConsolidation([NotNull] fwb17Parser.GoodsConsolidationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.dimensions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDimensions([NotNull] fwb17Parser.DimensionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.volume"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVolume([NotNull] fwb17Parser.VolumeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.uldNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUldNumber([NotNull] fwb17Parser.UldNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.shippersLoadAndCount"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShippersLoadAndCount([NotNull] fwb17Parser.ShippersLoadAndCountContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.harmonisedCommodityCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHarmonisedCommodityCode([NotNull] fwb17Parser.HarmonisedCommodityCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.countryOfOriginOfGoods"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCountryOfOriginOfGoods([NotNull] fwb17Parser.CountryOfOriginOfGoodsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.serviceCodeDetails"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitServiceCodeDetails([NotNull] fwb17Parser.ServiceCodeDetailsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.rateClassCodeBasisAndPercentage"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRateClassCodeBasisAndPercentage([NotNull] fwb17Parser.RateClassCodeBasisAndPercentageContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.weightInfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWeightInfo([NotNull] fwb17Parser.WeightInfoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.dimentionsDimNda"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDimentionsDimNda([NotNull] fwb17Parser.DimentionsDimNdaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.dimension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDimension([NotNull] fwb17Parser.DimensionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.awbIdentification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAwbIdentification([NotNull] fwb17Parser.AwbIdentificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.awbOriginAndDestination"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAwbOriginAndDestination([NotNull] fwb17Parser.AwbOriginAndDestinationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.quantityDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuantityDetail([NotNull] fwb17Parser.QuantityDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.volumeDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVolumeDetail([NotNull] fwb17Parser.VolumeDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.densityGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDensityGroup([NotNull] fwb17Parser.DensityGroupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.specialHandlingRequirements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpecialHandlingRequirements([NotNull] fwb17Parser.SpecialHandlingRequirementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.flightIdentification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFlightIdentification([NotNull] fwb17Parser.FlightIdentificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.firstDestinationCarrier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFirstDestinationCarrier([NotNull] fwb17Parser.FirstDestinationCarrierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.onwardDestinationCarrier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOnwardDestinationCarrier([NotNull] fwb17Parser.OnwardDestinationCarrierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.prepaidCollectChargeDeclarations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrepaidCollectChargeDeclarations([NotNull] fwb17Parser.PrepaidCollectChargeDeclarationsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.valueForCarriageDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValueForCarriageDeclaration([NotNull] fwb17Parser.ValueForCarriageDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.valueForCustomsDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValueForCustomsDeclaration([NotNull] fwb17Parser.ValueForCustomsDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.valueForInsuranceDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValueForInsuranceDeclaration([NotNull] fwb17Parser.ValueForInsuranceDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.otherChargeDetails"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOtherChargeDetails([NotNull] fwb17Parser.OtherChargeDetailsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.chargeLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChargeLine([NotNull] fwb17Parser.ChargeLineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.otherChargeItems"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOtherChargeItems([NotNull] fwb17Parser.OtherChargeItemsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.chargesOrTaxes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChargesOrTaxes([NotNull] fwb17Parser.ChargesOrTaxesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.totalCharges"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTotalCharges([NotNull] fwb17Parser.TotalChargesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.awbIssueDetails"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAwbIssueDetails([NotNull] fwb17Parser.AwbIssueDetailsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.authorisation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAuthorisation([NotNull] fwb17Parser.AuthorisationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.destinationCurrency"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDestinationCurrency([NotNull] fwb17Parser.DestinationCurrencyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.currencyConversionRate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCurrencyConversionRate([NotNull] fwb17Parser.CurrencyConversionRateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.ccChargesInDestinationCurrencyInner"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCcChargesInDestinationCurrencyInner([NotNull] fwb17Parser.CcChargesInDestinationCurrencyInnerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.chargesAtDestination"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChargesAtDestination([NotNull] fwb17Parser.ChargesAtDestinationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.totalCollectCharges"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTotalCollectCharges([NotNull] fwb17Parser.TotalCollectChargesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.noCommissionIndication"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoCommissionIndication([NotNull] fwb17Parser.NoCommissionIndicationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.commissionAmountOrPercentage"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommissionAmountOrPercentage([NotNull] fwb17Parser.CommissionAmountOrPercentageContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.commissionAmount"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommissionAmount([NotNull] fwb17Parser.CommissionAmountContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.commissionPercentage"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommissionPercentage([NotNull] fwb17Parser.CommissionPercentageContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.salesIncentiveDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSalesIncentiveDetail([NotNull] fwb17Parser.SalesIncentiveDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.salesIncentiveIndication"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSalesIncentiveIndication([NotNull] fwb17Parser.SalesIncentiveIndicationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.agentReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAgentReference([NotNull] fwb17Parser.AgentReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.otherCustSecurityAndRegulatCtrlInfoDet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOtherCustSecurityAndRegulatCtrlInfoDet([NotNull] fwb17Parser.OtherCustSecurityAndRegulatCtrlInfoDetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.accountDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccountDetail([NotNull] fwb17Parser.AccountDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitName([NotNull] fwb17Parser.NameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.nameDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNameDetail([NotNull] fwb17Parser.NameDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.streetAddress"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStreetAddress([NotNull] fwb17Parser.StreetAddressContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.streetAddressDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStreetAddressDetail([NotNull] fwb17Parser.StreetAddressDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.location"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocation([NotNull] fwb17Parser.LocationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.stateProvince"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStateProvince([NotNull] fwb17Parser.StateProvinceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.codedLocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCodedLocation([NotNull] fwb17Parser.CodedLocationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.postCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostCode([NotNull] fwb17Parser.PostCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.contactDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContactDetail([NotNull] fwb17Parser.ContactDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.accountDetailAgt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccountDetailAgt([NotNull] fwb17Parser.AccountDetailAgtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.cargoAgentCassOrParticipantId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCargoAgentCassOrParticipantId([NotNull] fwb17Parser.CargoAgentCassOrParticipantIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.participantId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParticipantId([NotNull] fwb17Parser.ParticipantIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.cargoAgentCassAddress"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCargoAgentCassAddress([NotNull] fwb17Parser.CargoAgentCassAddressContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.accountDetails"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccountDetails([NotNull] fwb17Parser.AccountDetailsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.place"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlace([NotNull] fwb17Parser.PlaceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.ssrDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSsrDetail([NotNull] fwb17Parser.SsrDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.osiItems"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOsiItems([NotNull] fwb17Parser.OsiItemsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.sofr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSofr([NotNull] fwb17Parser.SofrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.senderOfficeMessageAddress"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSenderOfficeMessageAddress([NotNull] fwb17Parser.SenderOfficeMessageAddressContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.senderOfficeFileReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSenderOfficeFileReference([NotNull] fwb17Parser.SenderOfficeFileReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.senderParticipantIdentification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSenderParticipantIdentification([NotNull] fwb17Parser.SenderParticipantIdentificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.supplementary1or2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSupplementary1or2([NotNull] fwb17Parser.Supplementary1or2Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.supplementaryShipmentInformation1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSupplementaryShipmentInformation1([NotNull] fwb17Parser.SupplementaryShipmentInformation1Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.supplementaryShipmentInformation2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSupplementaryShipmentInformation2([NotNull] fwb17Parser.SupplementaryShipmentInformation2Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.otherParticipantOfficeMessageAddress"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOtherParticipantOfficeMessageAddress([NotNull] fwb17Parser.OtherParticipantOfficeMessageAddressContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.opofr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpofr([NotNull] fwb17Parser.OpofrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.otherParticipantOfficeFileReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOtherParticipantOfficeFileReference([NotNull] fwb17Parser.OtherParticipantOfficeFileReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.otherParticipantIdentification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOtherParticipantIdentification([NotNull] fwb17Parser.OtherParticipantIdentificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.standardMessageIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStandardMessageIdentifier([NotNull] fwb17Parser.StandardMessageIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.messageTypeVersionNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageTypeVersionNumber([NotNull] fwb17Parser.MessageTypeVersionNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.lineIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLineIdentifier([NotNull] fwb17Parser.LineIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.chargeCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChargeCode([NotNull] fwb17Parser.ChargeCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.airlinePrefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirlinePrefix([NotNull] fwb17Parser.AirlinePrefixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.awbSerialNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAwbSerialNumber([NotNull] fwb17Parser.AwbSerialNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.airportCodeOfOrigin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirportCodeOfOrigin([NotNull] fwb17Parser.AirportCodeOfOriginContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.airportCodeOfDestitation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirportCodeOfDestitation([NotNull] fwb17Parser.AirportCodeOfDestitationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.shipmentDescriptionCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShipmentDescriptionCode([NotNull] fwb17Parser.ShipmentDescriptionCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.volumeCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVolumeCode([NotNull] fwb17Parser.VolumeCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.volumeAmount"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVolumeAmount([NotNull] fwb17Parser.VolumeAmountContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.densityIndicator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDensityIndicator([NotNull] fwb17Parser.DensityIndicatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.densityGroupInner"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDensityGroupInner([NotNull] fwb17Parser.DensityGroupInnerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.declaredValueForCarriage"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaredValueForCarriage([NotNull] fwb17Parser.DeclaredValueForCarriageContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.declaredValueForCustoms"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaredValueForCustoms([NotNull] fwb17Parser.DeclaredValueForCustomsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.amountOfInsurance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAmountOfInsurance([NotNull] fwb17Parser.AmountOfInsuranceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.noValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoValue([NotNull] fwb17Parser.NoValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.contactIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContactIdentifier([NotNull] fwb17Parser.ContactIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.contactNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContactNumber([NotNull] fwb17Parser.ContactNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.iataCargoAgentNumericCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIataCargoAgentNumericCode([NotNull] fwb17Parser.IataCargoAgentNumericCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.cargoAgentCassAddressInner"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCargoAgentCassAddressInner([NotNull] fwb17Parser.CargoAgentCassAddressInnerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.accountingInformationIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccountingInformationIdentifier([NotNull] fwb17Parser.AccountingInformationIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.day"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDay([NotNull] fwb17Parser.DayContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.month"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMonth([NotNull] fwb17Parser.MonthContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.year"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitYear([NotNull] fwb17Parser.YearContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.airportCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirportCode([NotNull] fwb17Parser.AirportCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.flightNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFlightNumber([NotNull] fwb17Parser.FlightNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.carrierCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCarrierCode([NotNull] fwb17Parser.CarrierCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.serviceCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitServiceCode([NotNull] fwb17Parser.ServiceCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.uldType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUldType([NotNull] fwb17Parser.UldTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.uldSerialNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUldSerialNumber([NotNull] fwb17Parser.UldSerialNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.uldOwnerCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUldOwnerCode([NotNull] fwb17Parser.UldOwnerCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.slac"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSlac([NotNull] fwb17Parser.SlacContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.harmonisedCommodityCodeInner"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHarmonisedCommodityCodeInner([NotNull] fwb17Parser.HarmonisedCommodityCodeInnerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.measurementUnitCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMeasurementUnitCode([NotNull] fwb17Parser.MeasurementUnitCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.lengthDimension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLengthDimension([NotNull] fwb17Parser.LengthDimensionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.widthDimension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWidthDimension([NotNull] fwb17Parser.WidthDimensionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.heightDimension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHeightDimension([NotNull] fwb17Parser.HeightDimensionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.rateOrCharge"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRateOrCharge([NotNull] fwb17Parser.RateOrChargeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.discount"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDiscount([NotNull] fwb17Parser.DiscountContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.commodityItemNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommodityItemNumber([NotNull] fwb17Parser.CommodityItemNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.uldRateClassType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUldRateClassType([NotNull] fwb17Parser.UldRateClassTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.rateClassCodeBasis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRateClassCodeBasis([NotNull] fwb17Parser.RateClassCodeBasisContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.rateClassCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRateClassCode([NotNull] fwb17Parser.RateClassCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.classRatePercentage"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassRatePercentage([NotNull] fwb17Parser.ClassRatePercentageContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.weightCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWeightCode([NotNull] fwb17Parser.WeightCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.weight"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWeight([NotNull] fwb17Parser.WeightContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.rateCombinationPoint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRateCombinationPoint([NotNull] fwb17Parser.RateCombinationPointContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.numberOfPieces"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberOfPieces([NotNull] fwb17Parser.NumberOfPiecesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.hwbColumnIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHwbColumnIdentifier([NotNull] fwb17Parser.HwbColumnIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.hwbRateLineNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHwbRateLineNumber([NotNull] fwb17Parser.HwbRateLineNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.pcIndWeightValuation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPcIndWeightValuation([NotNull] fwb17Parser.PcIndWeightValuationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.pcIndOtherCharges"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPcIndOtherCharges([NotNull] fwb17Parser.PcIndOtherChargesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.otherChargeCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOtherChargeCode([NotNull] fwb17Parser.OtherChargeCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.entitlementCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntitlementCode([NotNull] fwb17Parser.EntitlementCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.chargeIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChargeIdentifier([NotNull] fwb17Parser.ChargeIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.customsOriginCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCustomsOriginCode([NotNull] fwb17Parser.CustomsOriginCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.cassSettlementFactor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCassSettlementFactor([NotNull] fwb17Parser.CassSettlementFactorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.isoCurrencyCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIsoCurrencyCode([NotNull] fwb17Parser.IsoCurrencyCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.rateOfExchange"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRateOfExchange([NotNull] fwb17Parser.RateOfExchangeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.chargeAmount"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChargeAmount([NotNull] fwb17Parser.ChargeAmountContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.cassIndicator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCassIndicator([NotNull] fwb17Parser.CassIndicatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.specialHandlingCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpecialHandlingCode([NotNull] fwb17Parser.SpecialHandlingCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.airportCityCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAirportCityCode([NotNull] fwb17Parser.AirportCityCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.officeFunctionDesignator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOfficeFunctionDesignator([NotNull] fwb17Parser.OfficeFunctionDesignatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.companyDesignator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompanyDesignator([NotNull] fwb17Parser.CompanyDesignatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.participantIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParticipantIdentifier([NotNull] fwb17Parser.ParticipantIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.participantCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParticipantCode([NotNull] fwb17Parser.ParticipantCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.isoCountryCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIsoCountryCode([NotNull] fwb17Parser.IsoCountryCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.informationIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInformationIdentifier([NotNull] fwb17Parser.InformationIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.custSecurityAndRegulatCtrlInfoId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCustSecurityAndRegulatCtrlInfoId([NotNull] fwb17Parser.CustSecurityAndRegulatCtrlInfoIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.supplemCustSecurityAndRegulatCtrlInfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSupplemCustSecurityAndRegulatCtrlInfo([NotNull] fwb17Parser.SupplemCustSecurityAndRegulatCtrlInfoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.fileReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFileReference([NotNull] fwb17Parser.FileReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.nameInner"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNameInner([NotNull] fwb17Parser.NameInnerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.placeInner"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlaceInner([NotNull] fwb17Parser.PlaceInnerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.referenceNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReferenceNumber([NotNull] fwb17Parser.ReferenceNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.innerSupplementaryShipmentInformation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInnerSupplementaryShipmentInformation([NotNull] fwb17Parser.InnerSupplementaryShipmentInformationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.signature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSignature([NotNull] fwb17Parser.SignatureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.otherServiceInformationItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOtherServiceInformationItem([NotNull] fwb17Parser.OtherServiceInformationItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.specialServiceRequestInner"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpecialServiceRequestInner([NotNull] fwb17Parser.SpecialServiceRequestInnerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.accountingInformationInner"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccountingInformationInner([NotNull] fwb17Parser.AccountingInformationInnerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.accountNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccountNumber([NotNull] fwb17Parser.AccountNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.streetAddressInner"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStreetAddressInner([NotNull] fwb17Parser.StreetAddressInnerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.stateProvinceInner"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStateProvinceInner([NotNull] fwb17Parser.StateProvinceInnerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.postCodeInner"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostCodeInner([NotNull] fwb17Parser.PostCodeInnerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="fwb17Parser.natureAndQuantityOfGoods"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNatureAndQuantityOfGoods([NotNull] fwb17Parser.NatureAndQuantityOfGoodsContext context);
}
